// var msa = require("msa");

// your fasta file (advice: save it in a DOM node)
var fasta = ">seq1\n\
QVQLVQSGAEVKKPGASVKVSCKASGYTFTSYGISWVRQAPGQGLEWMGWISAYNGNTNYAQKLQGRVTMTTDTSTSTAYMELRSLRSDDTAVYYCARYMDVWGQGTLVTVSS\n\
>seq2\n\
QVQLVQSGAEVKKPGASVKVSCKASGYTFTSYGISWVRQAPGQGLEWMGWISAYNGNTNYAQKLQGRVTMTTDTSTSTAYMELRSLRSDDTAVYYCARGYDYWGQGTLVTVSS\n\
>seq3\n\
QVQLVQSGAEVKKPGASVKVSCKASGYTFTSYGISWVRQAPGQGLEWMGWISAYNGNTNYAQKLQGRVTMTTDTSTSTAYMELRSLRSDDTAVYYCAR  D WGQGTLVTVSS\n\
>seq4\n\
QVQLVQSGAEVKKPGASVKVSCKASGYTFTSYGISWVRQAPGQGLEWMGWISAYNGNTNYAQKLQGRVTMTTDTSTSTAYMELRSLRSDDTAVYYCARY";

// parsed array of the sequences
var seqs =  msa.io.fasta.parse(fasta);

var rootDiv = document.querySelector('#msa_container');

var m = msa({
     el: rootDiv,
     seqs: seqs
});
m.render();